### ISSUE TITLE
Can't access meta-llama/Llama-2-7b using llmstudio cli tool

### ISSUE THREAD

**Issue by sunilswain** [h2oai/h2o-llmstudio#725]
Hey
I've trying to use llmstudio cli since I do not have enough resources required by the H2o llmstudio. So I use Kaggle to run my cli tool. 
But anyways, I'm trying to train Llama-2-7b on my own dataset, and it gives me this error

> 
> Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-2-7b/resolve/main/config.json.
> Access to model meta-llama/Llama-2-7b is restricted. You must be authenticated to access it.
> all done

I know I do have access to this repo. I want to know, how can I authenticate myself while I'm using llmstudio?

Thanks

this is my config.yaml
```yaml
architecture:
    backbone_dtype: int8
    force_embedding_gradients: false
    gradient_checkpointing: true
    intermediate_dropout: 0.0
    pretrained: true
    pretrained_weights: ''
augmentation:
    neftune_noise_alpha: 0.0
    random_parent_probability: 0.0
    skip_parent_probability: 0.0
    token_mask_probability: 0.0
dataset:
    add_eos_token_to_answer: true
    add_eos_token_to_prompt: true
    add_eos_token_to_system: true
    answer_column: output_prompt
    chatbot_author: DataTeam
    chatbot_name: EsspLGPT
    data_sample: 1.0
    data_sample_choice:
    - Train
    - Validation
    limit_chained_samples: true
    mask_prompt_labels: true
    parent_id_column: None
    personalize: False
    prompt_column:
    - input_prompt
    system_column: None
    text_answer_separator: <|answer|>
    text_prompt_start: <|prompt|>
    text_system_start: <|system|>
    train_dataframe: data/EssplTravelPolicyQA/qa_train.csv
    validation_dataframe: data/EssplTravelPolicyQA/qa_val.csv
    validation_size: 0.01
    validation_strategy: automatic
environment:
    compile_model: false
    deepspeed_allgather_bucket_size: 1000000
    deepspeed_method: ZeRO2
    deepspeed_reduce_bucket_size: 1000000
    deepspeed_stage3_param_persistence_threshold: 1000000
    deepspeed_stage3_prefetch_bucket_size: 1000000
    find_unused_parameters: false
    gpus:
    - '0'
    - '1'
    huggingface_branch: main
    mixed_precision: false
    number_of_workers: 1
    seed: -1
    trust_remote_code: false
    use_deepspeed: false
experiment_name: EssplTravelPolicyFT
llm_backbone: meta-llama/Llama-2-7b
logging:
    logger: None
    neptune_project: Zoo/h2o-llm
output_directory: EssplTravelPolicyFTExperiment
prediction:
    batch_size_inference: 0
    do_sample: false
    max_length_inference: 256
    max_time: 120.0
    metric: BLEU
    metric_gpt_model: gpt-3.5-turbo-0301
    metric_gpt_template: general
    min_length_inference: 2
    num_beams: 1
    num_history: 4
    repetition_penalty: 1.1
    stop_tokens: ''
    temperature: 0.0
    top_k: 0
    top_p: 1.0
problem_type: text_causal_language_modeling
tokenizer:
    add_prompt_answer_tokens: false
    max_length: 1072
    max_length_answer: 512
    max_length_prompt: 1600
    padding_quantile: 1.0
    use_fast: true
training:
    batch_size: 2
    differential_learning_rate: 1.0e-05
    differential_learning_rate_layers: []
    drop_last_batch: true
    epochs: 1
    evaluate_before_training: false
    evaluation_epochs: 1.0
    grad_accumulation: 1
    gradient_clip: 0.0
    learning_rate: 0.0001
    lora: true
    lora_alpha: 16
    lora_dropout: 0.05
    lora_r: 4
    lora_target_modules: ''
    loss_function: TokenAveragedCrossEntropy
    optimizer: AdamW
    save_best_checkpoint: false
    schedule: Cosine
    train_validation_data: false
    use_flash_attention_2: false
    warmup_epochs: 0.1
    weight_decay: 0.0
```
